ALTER TABLE opciones_menu ADD COLUMN tipo_menu INTEGER NOT NULL;
ALTER TABLE opciones_menu ADD COLUMN habilitado TINYINT NOT NULL DEFAULT 1;
ALTER TABLE asignaturas ADD COLUMN habilitado TINYINT NOT NULL  DEFAULT 1;
ALTER TABLE docentes ADD COLUMN habilitado TINYINT NOT NULL DEFAULT 1;